// apps/demos/Demos/Chat/Overview/Vue/App.vue
<template>
  <DxChat
    :element-attr="{ id: 'user-chat' }"
    v-model:items="messages"
    v-model:user="currentUser"
    v-model:typing-users="userChatTypingUsers"
    @message-entered="onMessageEntered($event)"
    @typing-start="userChatTypingStart()"
    @typing-end="userChatTypingEnd()"
  />
  <DxChat
    :element-attr="{ id: 'support-chat' }"
    v-model:items="messages"
    v-model:user="supportAgent"
    v-model:typing-users="supportChatTypingUsers"
    @message-entered="onMessageEntered($event)"
    @typing-start="supportChatTypingStart()"
    @typing-end="supportChatTypingEnd()"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import DxChat from 'devextreme-vue/chat';
import { messages as initialMessages, supportAgent, currentUser } from './data.ts';

const messages = ref(initialMessages);
const userChatTypingUsers = ref([]);
const supportChatTypingUsers = ref([]);

function onMessageEntered(event) {
  messages.value = [...messages.value, event.message];
}

function userChatTypingStart() {
  supportChatTypingUsers.value = [currentUser];
}

function userChatTypingEnd() {
  supportChatTypingUsers.value = [];
}

function supportChatTypingStart() {
  userChatTypingUsers.value = [supportAgent];
}

function supportChatTypingEnd() {
  userChatTypingUsers.value = [];
}
</script>

<style scoped>
#app {
  display: flex;
  gap: 20px;
}

.dx-chat {
  height: 710px;
}

.dx-avatar {
  border: 1px solid var(--dx-color-border);
}
</style>

// apps/demos/Demos/Chat/Overview/ReactJs/App.js
import React, { useState } from 'react';
import Chat from 'devextreme-react/chat';
import { currentUser, supportAgent, initialMessages } from './data.js';

export default function App() {
  const [userChatTypingUsers, setUserChatTypingUsers] = useState([]);
  const [supportChatTypingUsers, setSupportChatTypingUsers] = useState([]);
  const [messages, setMessages] = useState(initialMessages);
  function onMessageEntered({ message }) {
    setMessages((prevMessages) => [...prevMessages, message]);
  }
  function typingStart({ user }) {
    if (user.id === currentUser.id) {
      setSupportChatTypingUsers([supportAgent]);
    } else {
      setUserChatTypingUsers([currentUser]);
    }
  }
  function typingEnd({ user }) {
    if (user.id === currentUser.id) {
      setSupportChatTypingUsers([]);
    } else {
      setUserChatTypingUsers([]);
    }
  }
  return (
    <React.Fragment>
      <Chat
        elementAttr={{ id: 'user-chat' }}
        user={currentUser}
        items={messages}
        onMessageEntered={onMessageEntered}
        onTypingStart={typingStart}
        onTypingEnd={typingEnd}
        typingUsers={userChatTypingUsers}
      />
      <Chat
        elementAttr={{ id: 'support-chat' }}
        user={supportAgent}
        items={messages}
        onMessageEntered={onMessageEntered}
        onTypingStart={typingStart}
        onTypingEnd={typingEnd}
        typingUsers={supportChatTypingUsers}
      />
    </React.Fragment>
  );
}
